<?php

namespace App\Support;

/** Etiquetas legibles para mensajes de validación del cuestionario pre-empleo. */
class CuestionarioValidacionLabels
{
    /** @return array<string, string> */
    public static function atributos(): array
    {
        return [
            'ultimo_nivel_academico' => 'último nivel académico',
            'formacion_academica' => 'formación académica',
            'econ_posee_propiedades' => '¿posee propiedades?',
            'econ_detalle_propiedades' => 'detalle de propiedades',
            'econ_posee_vehiculos' => '¿posee vehículos?',
            'econ_detalle_vehiculos' => 'detalle de vehículos',
            'econ_problemas_bancarios' => '¿problemas bancarios?',
            'econ_detalle_problemas_bancarios' => 'detalle de problemas bancarios',
            'econ_problemas_sat' => '¿problemas con SAT?',
            'econ_detalle_sat' => 'detalle de problemas con SAT',
            'econ_demandas_deudas' => '¿demandas por deudas?',
            'econ_detalle_demandas' => 'detalle de demandas por deudas',
            'econ_tiene_fiador' => '¿tiene fiador?',
            'econ_detalle_fiador' => 'detalle del fiador',
            'econ_pretension_salarial' => 'pretensión salarial',
            'salud_atencion_psicologica' => '¿atención psicológica?',
            'salud_detalle_psicologica' => 'detalle de atención psicológica',
            'salud_ideacion_dano' => '¿pensamientos de daño?',
            'salud_detalle_ideacion' => 'detalle sobre pensamientos de daño',
            'salud_tratamiento_medico' => '¿tratamiento médico?',
            'salud_detalle_tratamiento' => 'detalle del tratamiento médico',
            'salud_hospitalizaciones' => '¿hospitalizaciones?',
            'salud_detalle_hospitalizaciones' => 'detalle de hospitalizaciones',
            'salud_ausencias_enfermedad' => '¿ausencias por enfermedad?',
            'salud_detalle_ausencias' => 'detalle de ausencias por enfermedad',
            'salud_practica_deporte' => '¿practica deporte?',
            'salud_detalle_deporte' => 'detalle del deporte que practica',
            'salud_alergias' => '¿padece alergias?',
            'salud_detalle_alergias' => 'detalle de alergias',
            'salud_embarazada' => '¿está embarazada?',
            'salud_preocupaciones' => 'preocupaciones de salud',
            'salud_estado_general' => 'estado general de salud',
            'salud_tipo_sangre' => 'tipo de sangre',
            'salud_peso' => 'peso',
            'salud_estatura' => 'estatura',
            'salud_situacion_emocional' => 'situación emocional',
            'habito_tiempo_libre' => 'actividades en tiempo libre',
            'habito_alcohol_frecuencia' => 'frecuencia de consumo de alcohol',
            'tiene_tatuajes' => '¿tiene tatuajes?',
            'tiene_perforaciones' => '¿tiene perforaciones?',
            'tatuajes' => 'tatuajes',
            'perforaciones' => 'perforaciones',
            'deudas' => 'deudas',
            'empleos' => 'empleos anteriores',
            'hijos' => 'detalle de hijos',
            'hermanos' => 'hermanos',
            'nombres_completos' => 'nombres',
            'apellidos_completos' => 'apellidos',
            'fecha_nacimiento' => 'fecha de nacimiento',
            'estado_civil' => 'estado civil',
            'estado_civil_detalle' => 'estado civil',
            'tiene_hijos' => '¿tiene hijos?',
            'tiene_hermanos' => '¿tiene hermanos?',
            'personas_hogar' => 'personas en el hogar',
            'tipo_vivienda' => 'tipo de vivienda',
            'experiencia_previa' => 'experiencia laboral previa',
            'ingresos_principales' => 'ingresos principales',
            'gastos_vivienda' => 'gasto en vivienda',
            'tiene_deudas' => '¿tiene deudas?',
            'referencia1_nombre' => 'referencia personal 1 — nombre',
            'referencia1_telefono' => 'referencia personal 1 — teléfono',
            'referencia2_nombre' => 'referencia personal 2 — nombre',
            'referencia2_telefono' => 'referencia personal 2 — teléfono',
            'expareja_detalle_problemas' => 'detalle de problemas legales con expareja',
            'referencias_familiares' => 'referencias familiares',
            'referencias_personales' => 'referencias personales',
            'referencias_vecinales' => 'referencias vecinales',
            'referencias_laborales' => 'referencias laborales',
            'bienes' => 'bienes',
            'presupuesto' => 'presupuesto',
            'viv_tiempo_residencia' => 'tiempo en el domicilio actual',
            'viv_tipo_vivienda' => 'tipo de vivienda',
            'viv_propietario' => 'nombre del propietario / familiar',
            'viv_monto_alquiler' => 'monto de alquiler mensual',
            'viv_num_habitantes' => 'personas que habitan la vivienda',
            'viv_refs_ubicacion' => 'referencias para ubicar la vivienda',
            'viv_zona_riesgo' => 'zona de riesgo',
            'viv_detalle_zona_riesgo' => 'detalle de la zona de riesgo',
            'viv_direcciones_anteriores' => 'direcciones anteriores',
        ];
    }
}
