<?php

/**
 * Centro de Ayuda REPRO — manifiesto de artículos, FAQ y glosario.
 * Contenido HTML en resources/views/ayuda/articles/{slug}.blade.php
 */
return [
    'categorias' => [
        'inicio' => ['titulo' => 'Primeros pasos', 'icono' => 'bi-rocket-takeoff'],
        'flujos' => ['titulo' => 'Flujos completos', 'icono' => 'bi-arrow-repeat'],
        'modulos' => ['titulo' => 'Por módulo', 'icono' => 'bi-grid'],
    ],

    'modulos' => [
        'general' => ['titulo' => 'General', 'icono' => 'bi-house'],
        'ordenes' => ['titulo' => 'Órdenes', 'icono' => 'bi-file-text'],
        'cuestionarios' => ['titulo' => 'Cuestionarios', 'icono' => 'bi-card-checklist'],
        'empresas' => ['titulo' => 'Empresas y usuarios', 'icono' => 'bi-building'],
        'administracion' => ['titulo' => 'Administración', 'icono' => 'bi-gear'],
        'reportes' => ['titulo' => 'Reportes', 'icono' => 'bi-graph-up'],
    ],

    'articulos' => [
        // ── INICIO ──────────────────────────────────────────────
        [
            'slug' => 'inicio-repro',
            'titulo' => 'Inicio rápido — Panel REPRO',
            'categoria' => 'inicio',
            'modulo' => 'general',
            'icono' => 'bi-house',
            'audiencias' => ['repro'],
            'permisos' => [],
            'destacado' => true,
            'orden' => 1,
            'resumen' => 'Orientación en 5 minutos: panel de control, menú lateral y roles operativos.',
            'vista' => 'ayuda.articles.inicio-repro',
            'contexto' => ['dashboard'],
            'relacionados' => ['flujo-orden-completa', 'ordenes-detalle-evaluado', 'guia-usuario-sigor'],
        ],
        [
            'slug' => 'inicio-empresa',
            'titulo' => 'Inicio rápido — Portal Cliente',
            'categoria' => 'inicio',
            'modulo' => 'general',
            'icono' => 'bi-house',
            'audiencias' => ['empresa'],
            'permisos' => [],
            'destacado' => true,
            'orden' => 1,
            'resumen' => 'Cómo navegar el portal cliente, crear órdenes y dar seguimiento a evaluados.',
            'vista' => 'ayuda.articles.inicio-empresa',
            'contexto' => ['dashboard'],
            'relacionados' => ['crear-orden', 'seguimiento-ordenes', 'guia-usuario-sigor'],
        ],
        [
            'slug' => 'guia-usuario-sigor',
            'titulo' => 'Guía de usuario SIGOR',
            'categoria' => 'inicio',
            'modulo' => 'general',
            'icono' => 'bi-file-earmark-pdf',
            'audiencias' => ['repro', 'empresa'],
            'permisos' => [],
            'destacado' => true,
            'orden' => 2,
            'resumen' => 'Manual PDF: se ve en el navegador y se puede descargar si lo necesita.',
            'vista' => 'ayuda.articles.guia-usuario-sigor',
            'contexto' => ['ayuda'],
            'relacionados' => ['inicio-repro', 'inicio-empresa', 'flujo-orden-completa'],
        ],

        // ── FLUJOS ──────────────────────────────────────────────
        [
            'slug' => 'flujo-orden-completa',
            'titulo' => 'Flujo completo: de la orden al resultado',
            'categoria' => 'flujos',
            'modulo' => 'ordenes',
            'tiempo_lectura' => 6,
            'secciones' => [
                ['id' => 'diagrama', 'titulo' => 'Diagrama del flujo', 'icono' => 'bi-diagram-3'],
                ['id' => 'pasos', 'titulo' => 'Pasos detallados', 'icono' => 'bi-list-ol'],
                ['id' => 'estados', 'titulo' => 'Estados clave', 'icono' => 'bi-flag'],
            ],
            'icono' => 'bi-diagram-3',
            'audiencias' => ['repro', 'empresa'],
            'permisos' => ['ordenes.ver'],
            'destacado' => true,
            'orden' => 10,
            'resumen' => 'Ciclo completo: cliente crea orden → candidato llena formulario → REPRO procesa → resultados.',
            'vista' => 'ayuda.articles.flujo-orden-completa',
            'relacionados' => ['ordenes-detalle-evaluado', 'enlaces-candidato', 'crear-orden', 'correos-automaticos'],
        ],
        [
            'slug' => 'correos-automaticos',
            'titulo' => 'Correos automáticos del portal',
            'categoria' => 'flujos',
            'modulo' => 'general',
            'tiempo_lectura' => 5,
            'secciones' => [
                ['id' => 'candidato', 'titulo' => 'Correo al candidato', 'icono' => 'bi-person'],
                ['id' => 'cita', 'titulo' => 'Cita', 'icono' => 'bi-calendar-event'],
                ['id' => 'usuarios', 'titulo' => 'Alta de usuario', 'icono' => 'bi-person-plus'],
                ['id' => 'orden-sede', 'titulo' => 'Nueva orden (sede)', 'icono' => 'bi-building'],
                ['id' => 'resultados', 'titulo' => 'Resultados', 'icono' => 'bi-file-earmark-pdf'],
                ['id' => 'campana', 'titulo' => 'Solo campana', 'icono' => 'bi-bell'],
            ],
            'icono' => 'bi-envelope',
            'audiencias' => ['repro', 'empresa'],
            'permisos' => [],
            'destacado' => false,
            'orden' => 13,
            'resumen' => 'Qué correos manda el sistema: candidato (15 días, puesto), WhatsApp, cita, alta de usuario y resultados solo al reclutador o responsable.',
            'vista' => 'ayuda.articles.correos-automaticos',
            'relacionados' => ['enlaces-candidato', 'usuarios-empresa', 'flujo-orden-completa'],
        ],
        [
            'slug' => 'enlaces-candidato',
            'titulo' => 'Enlaces del candidato: copiar, invalidar y habilitar',
            'categoria' => 'flujos',
            'modulo' => 'ordenes',
            'tiempo_lectura' => 5,
            'screenshot' => 'enlaces-candidato.png',
            'secciones' => [
                ['id' => 'vista-simulada', 'titulo' => 'Vista simulada', 'icono' => 'bi-display'],
                ['id' => 'vigencia', 'titulo' => 'Vigencia del enlace', 'icono' => 'bi-calendar'],
                ['id' => 'acciones', 'titulo' => 'Acciones disponibles', 'icono' => 'bi-hand-index'],
                ['id' => 'flujo-vencido', 'titulo' => 'Flujo: enlace vencido', 'icono' => 'bi-arrow-repeat'],
                ['id' => 'referencia-botones', 'titulo' => 'Referencia de botones', 'icono' => 'bi-ui-checks'],
            ],
            'icono' => 'bi-link-45deg',
            'audiencias' => ['repro', 'empresa'],
            'permisos' => ['ordenes.ver'],
            'destacado' => true,
            'orden' => 12,
            'resumen' => 'Gestión de enlaces del cuestionario: vigencia mínima 15 días, invalidar y rehabilitar.',
            'vista' => 'ayuda.articles.enlaces-candidato',
            'contexto' => ['ordenes/*'],
            'botones' => [
                ['numero' => 1, 'nombre' => 'Enlace', 'accion' => 'Abre la URL del cuestionario del candidato en una pestaña nueva.', 'clase' => 'btn btn-outline-primary btn-sm', 'icono' => 'bi-link-45deg'],
                ['numero' => 2, 'nombre' => 'Copiar enlace', 'accion' => 'Copia la URL del cuestionario al portapapeles.', 'clase' => 'btn btn-outline-secondary btn-sm', 'icono' => 'bi-clipboard'],
                ['numero' => 3, 'nombre' => 'Correo', 'accion' => 'Reenvía el enlace por correo electrónico al candidato.', 'clase' => 'btn btn-outline-success btn-sm', 'icono' => 'bi-envelope'],
                ['numero' => 4, 'nombre' => 'Invalidar enlace', 'accion' => 'Bloquea el acceso del candidato hasta que REPRO habilite de nuevo el enlace.', 'clase' => 'btn btn-outline-danger btn-sm', 'icono' => 'bi-lock'],
                ['numero' => 5, 'nombre' => 'Habilitar enlace', 'accion' => 'Extiende la vigencia (según configuración, mínimo 15 días) y conserva el progreso parcial.', 'clase' => 'btn btn-outline-success btn-sm', 'icono' => 'bi-unlock'],
                ['numero' => 6, 'nombre' => 'Marcar recibido', 'accion' => 'Cierra el formulario: bloquea el enlace y marca el cuestionario como recibido.', 'clase' => 'btn btn-outline-secondary btn-sm', 'icono' => 'bi-check2-square'],
            ],
            'relacionados' => ['ordenes-detalle-evaluado', 'flujo-orden-completa', 'correos-automaticos'],
        ],

        // ── MÓDULOS REPRO ───────────────────────────────────────
        [
            'slug' => 'ordenes-detalle-evaluado',
            'titulo' => 'Detalle de orden: gestionar evaluados',
            'categoria' => 'modulos',
            'modulo' => 'ordenes',
            'tiempo_lectura' => 7,
            'screenshot' => 'ordenes-detalle-evaluado.png',
            'secciones' => [
                ['id' => 'vista-simulada', 'titulo' => 'Vista simulada', 'icono' => 'bi-display'],
                ['id' => 'cabecera', 'titulo' => 'Cabecera de la orden', 'icono' => 'bi-card-heading'],
                ['id' => 'accordion', 'titulo' => 'Accordion del evaluado', 'icono' => 'bi-person-badge'],
                ['id' => 'detalle-tecnico', 'titulo' => 'Detalle por sección', 'icono' => 'bi-list-nested'],
                ['id' => 'observacion', 'titulo' => 'Observación visible', 'icono' => 'bi-chat-left-text'],
                ['id' => 'archivar', 'titulo' => 'Archivar la orden', 'icono' => 'bi-archive'],
            ],
            'icono' => 'bi-person-badge',
            'audiencias' => ['repro'],
            'permisos' => ['ordenes.ver'],
            'destacado' => true,
            'orden' => 9,
            'resumen' => 'Accordion: estados, Programó/Encargado/Entrevistó, documentos, Word, preliminar (color y tablas).',
            'vista' => 'ayuda.articles.ordenes-detalle-evaluado',
            'contexto' => ['ordenes/*'],
            'relacionados' => ['enlaces-candidato', 'informe-word', 'calendario-citas', 'archivar-ordenes', 'correos-automaticos'],
        ],
        [
            'slug' => 'informe-word',
            'titulo' => 'Informe Word: vista previa y descarga',
            'categoria' => 'modulos',
            'modulo' => 'cuestionarios',
            'icono' => 'bi-file-earmark-word',
            'audiencias' => ['repro'],
            'permisos' => ['evaluaciones.editar'],
            'destacado' => false,
            'orden' => 21,
            'resumen' => 'Generar borrador Word, vista previa en el editor y descarga del informe .docx.',
            'vista' => 'ayuda.articles.informe-word',
            'contexto' => ['cuestionarios/*/editar'],
            'relacionados' => ['cuestionarios-gestion', 'ordenes-detalle-evaluado'],
        ],
        [
            'slug' => 'cuestionarios-gestion',
            'titulo' => 'Gestión de cuestionarios',
            'categoria' => 'modulos',
            'modulo' => 'cuestionarios',
            'icono' => 'bi-card-checklist',
            'audiencias' => ['repro'],
            'permisos' => ['cuestionarios.ver'],
            'destacado' => false,
            'orden' => 22,
            'resumen' => 'Listado, WhatsApp al candidato, consulta, edición, PDF y foto. Órdenes archivadas no aparecen.',
            'vista' => 'ayuda.articles.cuestionarios-gestion',
            'contexto' => ['cuestionarios', 'cuestionarios/*'],
            'relacionados' => ['informe-word', 'historial-dpi', 'archivar-ordenes'],
        ],
        [
            'slug' => 'calendario-citas',
            'titulo' => 'Calendario y programación de citas',
            'categoria' => 'modulos',
            'modulo' => 'ordenes',
            'icono' => 'bi-calendar-event',
            'audiencias' => ['repro'],
            'permisos' => ['calendario.ver'],
            'destacado' => false,
            'orden' => 23,
            'resumen' => 'Programar, reprogramar y cancelar citas. Excel del calendario. Columnas Programó y Entrevistó.',
            'vista' => 'ayuda.articles.calendario-citas',
            'contexto' => ['calendario', 'calendario/*'],
            'relacionados' => ['ordenes-detalle-evaluado', 'archivar-ordenes'],
        ],
        [
            'slug' => 'empresas-admin',
            'titulo' => 'Gestión de empresas cliente',
            'categoria' => 'modulos',
            'modulo' => 'empresas',
            'icono' => 'bi-building',
            'audiencias' => ['repro'],
            'permisos' => ['empresas.ver'],
            'destacado' => false,
            'orden' => 24,
            'resumen' => 'Alta, edición, logo y estado de empresas; PDF/Excel del padrón; usuarios principales y sedes.',
            'vista' => 'ayuda.articles.empresas-admin',
            'contexto' => ['empresas', 'show-empresa/*', 'edit-empresa/*'],
            'relacionados' => ['reportes-modulo'],
        ],
        [
            'slug' => 'historial-dpi',
            'titulo' => 'Historial por DPI o nombre',
            'categoria' => 'modulos',
            'modulo' => 'cuestionarios',
            'icono' => 'bi-search',
            'audiencias' => ['repro'],
            'permisos' => ['historial_dpi.ver'],
            'destacado' => false,
            'orden' => 25,
            'resumen' => 'Buscar un candidato en evaluaciones previas por DPI o nombre. No incluye órdenes archivadas.',
            'vista' => 'ayuda.articles.historial-dpi',
            'contexto' => ['cuestionarios/historial-dpi'],
            'relacionados' => ['cuestionarios-gestion', 'archivar-ordenes'],
        ],
        [
            'slug' => 'reportes-modulo',
            'titulo' => 'Reportes y exportaciones',
            'categoria' => 'modulos',
            'modulo' => 'reportes',
            'icono' => 'bi-graph-up',
            'audiencias' => ['repro', 'empresa'],
            'permisos' => ['reportes.ver'],
            'destacado' => false,
            'orden' => 26,
            'resumen' => 'INFORMES DE EMPRESAS: filtros de sede y fechas; exportar PDF y Excel.',
            'vista' => 'ayuda.articles.reportes-modulo',
            'contexto' => ['reportes/evaluaciones', 'reportes/empresas'],
            'relacionados' => ['flujo-orden-completa', 'archivar-ordenes'],
        ],
        [
            'slug' => 'configuracion-sistema',
            'titulo' => 'Configuración del sistema',
            'categoria' => 'modulos',
            'modulo' => 'administracion',
            'icono' => 'bi-gear',
            'audiencias' => ['repro'],
            'permisos' => [],
            'solo_admin' => true,
            'destacado' => false,
            'orden' => 27,
            'resumen' => 'Logo, moneda, vigencia de enlaces, visibilidad de historial para clientes.',
            'vista' => 'ayuda.articles.configuracion-sistema',
            'contexto' => ['config'],
            'relacionados' => ['enlaces-candidato'],
        ],
        [
            'slug' => 'seguridad-usuarios',
            'titulo' => 'Usuarios, roles y permisos REPRO',
            'categoria' => 'modulos',
            'modulo' => 'administracion',
            'tiempo_lectura' => 6,
            'secciones' => [
                ['id' => 'acceso', 'titulo' => 'Dónde se administra', 'icono' => 'bi-door-open'],
                ['id' => 'tipos', 'titulo' => 'Tipos de usuario', 'icono' => 'bi-people'],
                ['id' => 'editar-usuario', 'titulo' => 'Crear y editar', 'icono' => 'bi-pencil-square'],
                ['id' => 'roles', 'titulo' => 'Roles del sistema', 'icono' => 'bi-shield-check'],
                ['id' => 'eliminar', 'titulo' => 'Eliminar un usuario', 'icono' => 'bi-person-x'],
                ['id' => 'permisos-ordenes', 'titulo' => 'Permiso editar órdenes', 'icono' => 'bi-file-earmark-text'],
                ['id' => 'excel-fotos', 'titulo' => 'Excel y foto', 'icono' => 'bi-file-earmark-excel'],
                ['id' => 'roles-prueba', 'titulo' => 'Roles de prueba', 'icono' => 'bi-flask'],
            ],
            'icono' => 'bi-shield-lock',
            'audiencias' => ['repro'],
            'permisos' => [],
            'solo_admin' => true,
            'destacado' => true,
            'orden' => 28,
            'resumen' => 'Crear y editar usuarios, Excel del listado, foto, permisos, roles de prueba (QZ Temporal) y desactivar cuentas.',
            'vista' => 'ayuda.articles.seguridad-usuarios',
            'contexto' => ['users', 'edit-user/*', 'add-user', 'show-user/*', 'admin/roles', 'admin/roles/*', 'admin/roles/*/edit'],
            'relacionados' => ['archivar-ordenes', 'usuarios-empresa'],
        ],
        [
            'slug' => 'archivar-ordenes',
            'titulo' => 'Archivar órdenes',
            'categoria' => 'modulos',
            'modulo' => 'ordenes',
            'tiempo_lectura' => 4,
            'secciones' => [
                ['id' => 'quien', 'titulo' => 'Quién puede archivar', 'icono' => 'bi-shield-lock'],
                ['id' => 'que-oculta', 'titulo' => 'Qué deja de verse', 'icono' => 'bi-eye-slash'],
                ['id' => 'consultar', 'titulo' => 'Ver archivadas', 'icono' => 'bi-archive'],
                ['id' => 'no-confundir', 'titulo' => 'No confundir con', 'icono' => 'bi-slash-circle'],
            ],
            'icono' => 'bi-archive',
            'audiencias' => ['repro'],
            'permisos' => [],
            'solo_admin' => true,
            'destacado' => false,
            'orden' => 29,
            'resumen' => 'Archivar oculta la orden y a sus evaluados de candidatos, historial DPI, calendario y reportes. El expediente se conserva.',
            'vista' => 'ayuda.articles.archivar-ordenes',
            'contexto' => ['ordenes'],
            'relacionados' => ['ordenes-detalle-evaluado', 'historial-dpi', 'cuestionarios-gestion', 'seguridad-usuarios'],
        ],

        // ── MÓDULOS EMPRESA ─────────────────────────────────────
        [
            'slug' => 'crear-orden',
            'titulo' => 'Crear una nueva orden',
            'categoria' => 'modulos',
            'modulo' => 'ordenes',
            'tiempo_lectura' => 5,
            'screenshot' => 'crear-orden.png',
            'secciones' => [
                ['id' => 'vista-simulada', 'titulo' => 'Vista simulada', 'icono' => 'bi-display'],
                ['id' => 'acceso', 'titulo' => 'Acceso', 'icono' => 'bi-door-open'],
                ['id' => 'pasos', 'titulo' => 'Paso a paso', 'icono' => 'bi-list-ol'],
                ['id' => 'despues', 'titulo' => 'Después de crear', 'icono' => 'bi-check2-circle'],
            ],
            'icono' => 'bi-file-plus',
            'audiencias' => ['empresa'],
            'permisos' => ['ordenes.crear'],
            'destacado' => true,
            'orden' => 8,
            'resumen' => 'Formulario paso a paso: empresa, evaluados, tipos de servicio y envío.',
            'vista' => 'ayuda.articles.crear-orden',
            'contexto' => ['ordenes/create'],
            'relacionados' => ['flujo-orden-completa', 'seguimiento-ordenes'],
        ],
        [
            'slug' => 'seguimiento-ordenes',
            'titulo' => 'Seguimiento de mis órdenes',
            'categoria' => 'modulos',
            'modulo' => 'ordenes',
            'icono' => 'bi-list-check',
            'audiencias' => ['empresa'],
            'permisos' => ['ordenes.ver'],
            'destacado' => true,
            'orden' => 31,
            'resumen' => 'Listado de órdenes, Excel, estados, evaluados y acciones disponibles para el cliente.',
            'vista' => 'ayuda.articles.seguimiento-ordenes',
            'contexto' => ['ordenes'],
            'relacionados' => ['enlaces-candidato', 'resultados-cliente'],
        ],
        [
            'slug' => 'documentos-candidato',
            'titulo' => 'Subir papelería del candidato',
            'categoria' => 'modulos',
            'modulo' => 'ordenes',
            'icono' => 'bi-cloud-upload',
            'audiencias' => ['empresa'],
            'permisos' => ['documentos.subir'],
            'destacado' => false,
            'orden' => 32,
            'resumen' => 'Tipos de documento, tamaño máximo y verificación por REPRO.',
            'vista' => 'ayuda.articles.documentos-candidato',
            'contexto' => ['ordenes/*'],
            'relacionados' => ['seguimiento-ordenes'],
        ],
        [
            'slug' => 'resultados-cliente',
            'titulo' => 'Ver y descargar resultados',
            'categoria' => 'modulos',
            'modulo' => 'ordenes',
            'icono' => 'bi-file-earmark-pdf',
            'audiencias' => ['empresa'],
            'permisos' => ['resultados.ver'],
            'destacado' => false,
            'orden' => 33,
            'resumen' => 'Cuándo aparecen los resultados, preliminares vs finales y descarga.',
            'vista' => 'ayuda.articles.resultados-cliente',
            'contexto' => ['ordenes/*'],
            'relacionados' => ['seguimiento-ordenes', 'flujo-orden-completa'],
        ],
        [
            'slug' => 'estado-procesos',
            'titulo' => 'Estado de procesos (cuestionarios)',
            'categoria' => 'modulos',
            'modulo' => 'cuestionarios',
            'icono' => 'bi-clipboard-check',
            'audiencias' => ['empresa'],
            'permisos' => ['cuestionarios.ver'],
            'destacado' => false,
            'orden' => 34,
            'resumen' => 'Avance del cuestionario de cada candidato y WhatsApp al candidato.',
            'vista' => 'ayuda.articles.estado-procesos',
            'contexto' => ['cuestionarios', 'cuestionarios/*'],
            'relacionados' => ['seguimiento-ordenes'],
        ],
        [
            'slug' => 'usuarios-empresa',
            'titulo' => 'Gestionar usuarios de mi empresa',
            'categoria' => 'modulos',
            'modulo' => 'empresas',
            'icono' => 'bi-people',
            'audiencias' => ['empresa'],
            'permisos' => [],
            'solo_principal' => true,
            'destacado' => false,
            'orden' => 35,
            'resumen' => 'Crear trabajadores/reclutadores (correo de bienvenida) y asignar permisos individuales.',
            'vista' => 'ayuda.articles.usuarios-empresa',
            'contexto' => ['empresa/usuarios', 'empresa/usuarios/*'],
            'relacionados' => ['permisos-trabajador', 'correos-automaticos'],
        ],
        [
            'slug' => 'permisos-trabajador',
            'titulo' => 'Usuario principal vs trabajador',
            'categoria' => 'modulos',
            'modulo' => 'empresas',
            'icono' => 'bi-person-lock',
            'audiencias' => ['empresa'],
            'permisos' => [],
            'solo_principal' => true,
            'destacado' => false,
            'orden' => 36,
            'resumen' => 'Diferencias de acceso entre gerente RRHH y reclutador/asistente.',
            'vista' => 'ayuda.articles.permisos-trabajador',
            'contexto' => ['empresa/usuarios'],
            'relacionados' => ['usuarios-empresa', 'crear-orden'],
        ],
    ],

    'faq' => [
        [
            'pregunta' => '¿Dónde está la guía de usuario SIGOR?',
            'respuesta' => 'En el Centro de Ayuda, artículo «Guía de usuario SIGOR». Se abre en el navegador; la descarga es opcional.',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-file-earmark-pdf',
            'articulo' => 'guia-usuario-sigor',
        ],
        [
            'pregunta' => '¿Cómo le escribo al candidato por WhatsApp?',
            'respuesta' => 'En Gestión de Cuestionario (REPRO) o Estado de Procesos (cliente) pulse el botón verde de WhatsApp. Solo aparece si el evaluado tiene teléfono. También hay icono junto al número en la columna Contacto.',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-whatsapp',
            'articulo' => 'correos-automaticos',
        ],
        [
            'pregunta' => 'El PDF de usuarios no abre, ¿hay Excel?',
            'respuesta' => 'Sí. En Administración → Usuarios use el botón verde Excel. El PDF sigue disponible; el Excel es el listado filtrado.',
            'audiencias' => ['repro'],
            'solo_admin' => true,
            'icono' => 'bi-file-earmark-excel',
            'articulo' => 'seguridad-usuarios',
        ],
        [
            'pregunta' => 'Creé un usuario desde la empresa y no le llegó el correo',
            'respuesta' => 'Al crear el trabajador ahora sí se envía el correo con usuario y contraseña. Pida revisar spam. Si el usuario ya existía de antes, use Recuperar contraseña o vuelva a crear uno nuevo.',
            'audiencias' => ['empresa'],
            'solo_principal' => true,
            'icono' => 'bi-envelope',
            'articulo' => 'usuarios-empresa',
        ],
        [
            'pregunta' => 'No puedo subir la foto del usuario o el logo de la empresa',
            'respuesta' => 'Ya se corrigió la ruta de guardado. Vuelva a intentar desde editar usuario o editar empresa (PNG/JPG). Si sigue fallando, avise a soporte.',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-image',
            'articulo' => 'seguridad-usuarios',
        ],
        [
            'pregunta' => '¿Qué es el rol Empresa QZ Temporal y por qué no lo puedo borrar?',
            'respuesta' => 'Es un rol de prueba. No da acceso al panel REPRO: eso lo marca el tipo de usuario (empresa). Si el cliente ya entra bien al portal, déjelo. Para borrar el rol, en Usuarios edite a esas personas, elija Usuario Empresa y guarde.',
            'audiencias' => ['repro'],
            'solo_admin' => true,
            'icono' => 'bi-flask',
            'articulo' => 'seguridad-usuarios',
        ],
        [
            'pregunta' => '¿El correo del candidato sigue diciendo 30 días?',
            'respuesta' => 'No. Ya no muestra «30 días restantes» ni fecha límite. Lleva el puesto y pide completarlo lo antes posible. El enlace nuevo dura 15 días.',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-envelope',
            'articulo' => 'correos-automaticos',
        ],
        [
            'pregunta' => '¿Por qué el enlace del candidato dice "vencido" o "no válido"?',
            'respuesta' => 'El enlace puede haber expirado (vigencia mínima 15 días configurable), haber sido invalidado manualmente por REPRO, o el candidato copió una URL incompleta. REPRO puede habilitar el enlace de nuevo desde el detalle de la orden.',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-link-45deg',
            'articulo' => 'enlaces-candidato',
        ],
        [
            'pregunta' => '¿Cuánto dura el enlace del cuestionario?',
            'respuesta' => 'La vigencia se configura en Administración → Configuración (mínimo 15 días). Al habilitar un enlace invalidado, se extiende por el número de días configurado.',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-calendar',
            'articulo' => 'enlaces-candidato',
        ],
        [
            'pregunta' => '¿Puede el reclutador llenar el formulario por el candidato?',
            'respuesta' => 'No. El cuestionario debe ser completado únicamente por el aplicante. El reclutador puede subir papelería adjunta, pero no reemplaza al candidato en el formulario.',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-person-x',
            'articulo' => 'crear-orden',
        ],
        [
            'pregunta' => '¿Por qué no veo el botón "Nueva Orden"?',
            'respuesta' => 'Solo los usuarios principales de la empresa o trabajadores con permiso "Crear órdenes" pueden crear órdenes. Contacte al administrador de su empresa para solicitar el permiso.',
            'audiencias' => ['empresa'],
            'icono' => 'bi-lock',
            'articulo' => 'permisos-trabajador',
        ],
        [
            'pregunta' => '¿Cómo filtro las órdenes por reclutador?',
            'respuesta' => 'En Mis Órdenes use el filtro Reclutador. Puede ver los procesos de una persona o solo las órdenes sin asignar. El Excel del listado usa el mismo filtro. El gerente ve todos los procesos de su empresa; cada reclutador ve según el modo de visibilidad (compartido o solo propios).',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-funnel',
            'articulo' => 'seguimiento-ordenes',
        ],
        [
            'pregunta' => '¿Cuándo el cliente puede ver los resultados?',
            'respuesta' => 'REPRO controla la visibilidad. Los resultados aparecen en el detalle de la orden cuando REPRO los marca como visibles para la empresa.',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-file-earmark-pdf',
            'articulo' => 'resultados-cliente',
        ],
        [
            'pregunta' => '¿Por qué dejaron de llegar los correos?',
            'respuesta' => 'Si el portal muestra un aviso amarillo o rojo de límite diario, el servicio de correo (Resend) llegó a su tope (100/día por defecto). Los avisos en SIGOR sí quedan. Se reanudan al día siguiente o al subir el plan. MAIL_ALERTA_ACTIVA / MAIL_LIMITE_DIARIO se configuran en el servidor.',
            'audiencias' => ['repro'],
            'icono' => 'bi-envelope-exclamation',
            'articulo' => 'correos-automaticos',
        ],
        [
            'pregunta' => '¿A quién le llega el correo de resultados?',
            'respuesta' => 'Al reclutador asignado, aunque el proceso no sea confidencial. Si no hay reclutador y la creó la empresa, a quien la creó. Si la creó REPRO, al titular. El gerente ve la orden en SIGOR; no recibe ese correo si no es el responsable. Confidencial solo recorta quién ve el proceso, no ensancha el correo.',
            'audiencias' => ['repro', 'empresa'],
            'icono' => 'bi-envelope-check',
            'articulo' => 'correos-automaticos',
        ],
        [
            'pregunta' => '¿Qué significa "Marcar recibido" en el enlace del candidato?',
            'respuesta' => 'Bloquea el enlace del candidato y marca el cuestionario como recibido, aunque no haya sido completado al 100%. Use con precaución.',
            'audiencias' => ['repro'],
            'icono' => 'bi-check2-square',
            'articulo' => 'enlaces-candidato',
        ],
        [
            'pregunta' => 'La vista previa Word tarda o no carga, ¿qué hago?',
            'respuesta' => 'Espere hasta 90 segundos (el sistema cancela automáticamente si excede ese tiempo). Si persiste, descargue el .docx directamente con "Descargar informe Word".',
            'audiencias' => ['repro'],
            'permisos' => ['evaluaciones.editar'],
            'icono' => 'bi-file-earmark-word',
            'articulo' => 'informe-word',
        ],
        [
            'pregunta' => '¿Cómo busco un candidato que ya fue evaluado antes?',
            'respuesta' => 'Use "Historial por DPI o nombre" en el menú Evaluaciones (requiere permiso). También puede buscar por DPI desde el Panel de Control del portal cliente.',
            'audiencias' => ['repro'],
            'permisos' => ['historial_dpi.ver'],
            'icono' => 'bi-search',
            'articulo' => 'historial-dpi',
        ],
        [
            'pregunta' => '¿Qué diferencia hay entre invalidar y deshabilitar el cuestionario?',
            'respuesta' => 'Invalidar enlace: bloquea acceso temporal hasta habilitar. Marcar recibido / deshabilitar: cierra definitivamente el acceso del candidato y marca como recibido.',
            'audiencias' => ['repro'],
            'icono' => 'bi-shuffle',
            'articulo' => 'enlaces-candidato',
        ],
        [
            'pregunta' => '¿Cómo agrego un trabajador con permisos limitados?',
            'respuesta' => 'Como usuario principal, vaya a Mi Empresa → Usuarios → Crear. Asigne solo los permisos necesarios (ver órdenes, subir documentos, etc.).',
            'audiencias' => ['empresa'],
            'solo_principal' => true,
            'icono' => 'bi-people',
            'articulo' => 'usuarios-empresa',
        ],
        [
            'pregunta' => '¿Por qué al editar un usuario aparecía un rol nuevo?',
            'respuesta' => 'El sistema guarda los permisos individuales de ese empleado de forma interna. Eso ya no se muestra en Gestión de Roles. Para cambiar lo que puede hacer, edite el usuario y marque o desmarque los permisos.',
            'audiencias' => ['repro'],
            'solo_admin' => true,
            'icono' => 'bi-shield',
            'articulo' => 'seguridad-usuarios',
        ],
        [
            'pregunta' => '¿Por qué no puedo eliminar algunos usuarios?',
            'respuesta' => 'Eliminar desactiva la cuenta; no borra el historial. No se puede eliminar el último administrador ni su propia cuenta. El titular de una empresa sí se puede desactivar; asigne otro principal si la empresa sigue operando. Solo un administrador ve el botón Eliminar.',
            'audiencias' => ['repro'],
            'solo_admin' => true,
            'icono' => 'bi-person-x',
            'articulo' => 'seguridad-usuarios',
        ],
        [
            'pregunta' => 'El empleado tiene permiso de editar órdenes y no lo deja entrar',
            'respuesta' => 'Marque Ver órdenes y Editar órdenes en Usuarios → editar ese empleado, y guarde. Ya no hace falta que figure el rol «repro» en la lista de roles.',
            'audiencias' => ['repro'],
            'solo_admin' => true,
            'icono' => 'bi-file-earmark-text',
            'articulo' => 'seguridad-usuarios',
        ],
        [
            'pregunta' => 'Archivé una orden y el evaluado sigue saliendo en candidatos',
            'respuesta' => 'Al archivar, el evaluado no debe aparecer en Gestión de Cuestionario ni en Historial por DPI. En Órdenes use el filtro Vista → Órdenes archivadas para consultar el expediente. Si sigue visible en las listas activas, avise a soporte.',
            'audiencias' => ['repro'],
            'solo_admin' => true,
            'icono' => 'bi-archive',
            'articulo' => 'archivar-ordenes',
        ],
    ],

    'glosario' => [
        ['termino' => 'Orden de evaluación', 'definicion' => 'Solicitud formal de una o más evaluaciones (polígrafo, VSA, socioeconómico, etc.) para uno o más candidatos.', 'articulo' => 'flujo-orden-completa'],
        ['termino' => 'Evaluado', 'definicion' => 'Candidato incluido en una orden. Cada evaluado tiene su propio enlace, estados y documentos.', 'articulo' => 'ordenes-detalle-evaluado'],
        ['termino' => 'Estado de evaluación', 'definicion' => 'Progreso operativo: Pendiente de Evaluación, En Proceso, Entregado, Cancelado, Desistió, etc.', 'articulo' => 'ordenes-detalle-evaluado'],
        ['termino' => 'Estado de formulario', 'definicion' => 'Avance del cuestionario: Pendiente de Llenar, Link Enviado, Recibido, Vencido.', 'articulo' => 'enlaces-candidato'],
        ['termino' => 'Estado de programación', 'definicion' => 'Cita agendada: Sin programar, Programado, Contactado, Desistió, Cancelado.', 'articulo' => 'calendario-citas'],
        ['termino' => 'Enlace del candidato', 'definicion' => 'URL única (/cuestionario/{token}) para que el candidato llene el formulario sin login.', 'articulo' => 'enlaces-candidato'],
        ['termino' => 'Usuario principal', 'definicion' => 'Titular de la cuenta empresa (principal=1). Acceso completo al portal cliente.', 'articulo' => 'permisos-trabajador'],
        ['termino' => 'Trabajador / Reclutador', 'definicion' => 'Sub-usuario empresa con permisos JSON individuales. Por defecto no puede crear órdenes. Si está asignado a la orden, recibe el correo de resultados aunque el proceso no sea confidencial.', 'articulo' => 'permisos-trabajador'],
        ['termino' => 'Proceso confidencial', 'definicion' => 'Recorta quién ve la orden en SIGOR (gerente + creador + reclutador). No decide el correo de resultados; ese va al responsable.', 'articulo' => 'correos-automaticos'],
        ['termino' => 'Informe Word', 'definicion' => 'Documento .docx generado desde las respuestas del cuestionario para redacción del informe final.', 'articulo' => 'informe-word'],
        ['termino' => 'Resultado preliminar / final', 'definicion' => 'Archivos PDF de evaluación subidos por REPRO. Visibilidad controlada hacia el cliente.', 'articulo' => 'resultados-cliente'],
        ['termino' => 'Papelería', 'definicion' => 'Documentos adjuntos del candidato (DPI, antecedentes, etc.) distintos del cuestionario en línea.', 'articulo' => 'documentos-candidato'],
        ['termino' => 'Sede REPRO', 'definicion' => 'Oficina física donde se realizan evaluaciones presenciales. Incluye contacto WhatsApp.'],
        ['termino' => 'Archivar orden', 'definicion' => 'El administrador oculta la orden y a sus evaluados de los listados de trabajo. El expediente se conserva; no se elimina.', 'articulo' => 'archivar-ordenes'],
        ['termino' => 'Eliminar usuario', 'definicion' => 'Desactiva la cuenta (deja de poder entrar). No borra historial de órdenes ni evaluaciones.', 'articulo' => 'seguridad-usuarios'],
        ['termino' => 'Permisos individuales', 'definicion' => 'Checkboxes de un empleado REPRO al editarlo en Usuarios. No aparecen como rol en Gestión de Roles.', 'articulo' => 'seguridad-usuarios'],
        ['termino' => 'Entrevistó', 'definicion' => 'Quién hizo la entrevista (entrevistador_id). Es independiente de Programó y Encargado. Botón «Autoasignarme entrevista».', 'articulo' => 'ordenes-detalle-evaluado'],
        ['termino' => 'WhatsApp al candidato', 'definicion' => 'Botón verde en el listado de cuestionarios que abre el chat con el teléfono del evaluado.', 'articulo' => 'cuestionarios-gestion'],
    ],
];
